server:
  port: 8760
spring:
  application:
    name: common
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

common:
  archaius:
    properties:
      one: one FROM:config.properties
